### ISSUE TITLE
Pact Consumer tests are failing

### ISSUE THREAD

**Issue by tristanHessell** [tristanHessell/mess-around#103]
**Describe the bug**
Pact Consumer tests are failing at the provider setup level with error `listen EADDRNOTAVAIL: address not available ::1:5000`

This has follow on effects of the actual tests failing due to there being no "server" to be able to test against.

**To Reproduce**
1. yarn run pact-c

**Expected behavior**
The tests passing.

**Desktop (please complete the following information):**
 - OS: Ubuntu MATE 18.04.2
 - Version 1.0.0

**Comment by tristanHessell** [comment]
Failures were due to my machine not allowing ipv6 on localhost (through the loopback `lo` network interface).

updating `sysctl.conf` with `net.ipv6.conf.lo.disable_ipv6 = 0` did the trick.

----
From a `pact` perspective, these failures were caused by the addition of testing for the ipv6 localhost address (`::1`), which came in here: https://github.com/pact-foundation/pact-js/compare/v9.1.1...v9.2.0. A ticket will be raised to see what can be done to improve the user experience when encountering errors like this.

**Comment by deekayw0n** [comment]
Happen to ever raise that ticket? ;) . Can you link here?

**Comment by tristanHessell** [comment]
@deekayw0n Thank you for keeping me honest! I completely forgot.

I will get onto that shortly
